### ISSUE TITLE
Error in sql scripts

### ISSUE THREAD

**Issue by chris-baumann-at** [UCY-eHealthLab/OpenNCP-Deployments#1]
First of all: Thanks for the docker version!

during the firt start (of docker-compose) the db container is created, which leads to the following error:
```
[Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/delete_openatna_etransaction.sql ERROR 1046 (3D000) at line 1: No database selected
db exited with code 1
dependency failed to start: container db is unhealthy
```

same in openncp_users.sql
```
[Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/openncp_users.sql  ERROR 1046 (3D000) at line 8: No database selected
```
The rest of the setup seems to work.

Thanks,
Chris

**Comment by psavva** [comment]
These are the initialization scripts we had on our server.

I think these will properly need to be reviewed, and understood how the database schemas should be created, and even if these should exist here...

In my opinion, it would be much better have proper database tracking system with change management like liquibase.

I see that epsos-configuration contains scripts: eg: epsos-configuration/EADC_resources/db/CREATE_EADC.sql
and more.

It would be great to get direction from the experts that know how to setup the system properly, and we can adjust the scripts (delete them, replace them, re-write them) and to get an stable system working from get go

**Comment by chris-baumann-at** [comment]
OK, thanks for the explanation.

> It would be great to get direction from the experts that know how to setup the system properly, and we can adjust the scripts (delete them, replace them, re-write them) and to get an stable system working from get go

Yes, indeed. It would be great, if there is a "single source", where ALL infos about the desired data-structure are collected, including sql-scripts for setting up a fresh, new & shiny database ...

**Comment by psavva** [comment]
Closed with PR https://github.com/UCY-eHealthLab/OpenNCP-Deployments/pull/3
